### ISSUE TITLE
需要手动创建目录结构

### ISSUE THREAD

**Issue by BppleMan** [joyneop/tiebatobook#1]
> * Run `$ node prefetch.js` to build metadata.
```
[ARR] trackingListThreadsId: ["5490057397","5490057398"]
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open './cache/tracking/trackingList-full.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
http://tieba.baidu.com/p/5475406470
    at Object.<anonymous> (/Users/BppleMan/Downloads/tiebatobook/prefetch.js:38:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```
纠结了五分钟，尝试手动mkdir，至少需要手动以下三个目录
```
./cache/tracking
./cache/tmp
./cache/tmp/html
```

**Comment by neruthes** [comment]
现在运行 `prefetch.js` 时会创建这三个目录。应该可以了吧。
